# Build and Push Docker Container

trigger:
  branches:
    include:
    - releases/*
  paths:
    exclude:
    - docs/*
    - tests/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
   containerRegistry: 'munique docker hub'
   command: 'login'
- task: Docker@2
  displayName: "Build and Push All-In-One Image (openmu)"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Startup/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu'
    tags: |
      $(Build.SourceBranchName)
      latest
- task: Docker@2
  displayName: "Build and Push AdminPanel Image (openmu-admin)"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/AdminPanel.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-admin'
    tags: |
      $(Build.SourceBranchName)
      latest
- task: Docker@2
  displayName: "Build and Push ChatServer Image"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/ChatServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-chat'
    tags: |
      $(Build.SourceBranchName)
      latest
- task: Docker@2
  displayName: "Build and Push ConnectServer Image (openmu-connect)"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/ConnectServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-connect'
    tags: |
      $(Build.SourceBranchName)
      latest
- task: Docker@2
  displayName: "Build and Push FriendServer Image (openmu-friend)"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/FriendServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-friend'
    tags: |
      $(Build.SourceBranchName)
      latest
- task: Docker@2
  displayName: "Build and Push GameServer Image (openmu-game)"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/GameServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-game'
    tags: |
      $(Build.SourceBranchName)
      latest
- task: Docker@2
  displayName: "Build and Push GuildServer Image (openmu-guild)"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/GuildServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-guild'
    tags: |
      $(Build.SourceBranchName)
      latest
- task: Docker@2
  displayName: "Build and Push LoginServer Image (openmu-login)"
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/LoginServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-login'
    tags: |
      $(Build.SourceBranchName)
      latest
