version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - openmu-startup

  openmu-startup:
    image: ${DOCKER_REGISTRY-}openmu
    container_name: openmu-startup
    restart: unless-stopped
    tty: true
    ports:
      - "80"
      - "55901:55901"
      - "55902:55902"
      - "55903:55903"
      - "44405:44405"
      - "55980:55980"
    environment:
      DB_HOST: database
      # ASPNETCORE_URLS: http://+:1234
    working_dir: /app/
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: openmu
      POSTGRES_USER: postgres
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data #store data on volume

volumes:
  dbdata:
