apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: login-state
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef: connectionStrings:state-store
auth:
  secretStore: secrets