name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish packages to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: publish MUnique.OpenMU.Network on version change
        uses: rohith/publish-nuget@e2920cdadd1ebe88751082afc324ca8170f35cd1
        with:
          PROJECT_FILE_PATH: src/Network/MUnique.OpenMU.Network.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          PACKAGE_NAME: MUnique.OpenMU.Network

      - name: publish MUnique.OpenMU.Network.Packets on version change
        uses: rohith/publish-nuget@e2920cdadd1ebe88751082afc324ca8170f35cd1
        with:
          PROJECT_FILE_PATH: src/Network/Packets/MUnique.OpenMU.Network.Packets.csproj
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          PACKAGE_NAME: MUnique.OpenMU.Network.Packets
